{
 "title": "Prusa Metrics MK4/C1",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ip",
    "label": "Printer",
    "query": {
     "query": "label_values(prusa_fan_speed,ip)"
    }
   },
   {
    "name": "active_extruder",
    "query": {
     "query": "query_result(max(prusa_active_extruder{ip=\"$ip\"}) >= 0  < 5 or vector (0))"
    }
   },
   {
    "name": "adjusted_active_extruder",
    "query": {
     "query": "query_result(vector($active_extruder)+1)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Printed File",
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "prusa_job_image{printer_address=\"$ip\"}",
     "legendFormat": "{{printer_job_path}}"
    }
   ]
  },
  {
   "title": "Printer Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(printer_name) (prusa_info{printer_address=\"$ip\"})",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Printer Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(printer_model) (prusa_info{printer_address=\"$ip\"})",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "Filament",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by(printer_filament) (prusa_material_info{printer_address=\"$ip\"})",
     "legendFormat": "{{printer_filament}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by(printer_state) (prusa_status_info{printer_address=\"$ip\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prusa_printing_progress_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Remaining time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_printing_time_remaining_seconds{printer_address=\"$ip\", printer_job_name!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overcurrent detected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_oc_inp{ip=\"$ip\"}",
     "legendFormat": "Input rail"
    },
    {
     "expr": "prusa_oc_nozz{ip=\"$ip\"}",
     "legendFormat": "Nozzle rail"
    }
   ]
  },
  {
   "title": "Temperature - Nozzle $adjusted_active_extruder",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(n) (prusa_temp_noz{ip=\"$ip\", n=\"$active_extruder\"})",
     "legendFormat": "Actual"
    },
    {
     "expr": "max by(n) (prusa_ttemp_noz{ip=\"$ip\", n=\"$active_extruder\"})",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Temperature - Heatbed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "prusa_temp_bed{ip=\"$ip\"}",
     "legendFormat": "Actual"
    },
    {
     "expr": "prusa_ttemp_bed{ip=\"$ip\"}",
     "legendFormat": "Target"
    }
   ]
  },
  {
   "title": "Loadcell",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 4, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "targets": [
    {
     "expr": "prusa_loadcell_value{ip=\"$ip\"}",
     "legendFormat": "Pressure"
    }
   ]
  },
  {
   "title": "Fan speeds",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_fan_measured{ip=\"$ip\"}",
     "legendFormat": "{{fan}}"
    },
    {
     "expr": "avg(prusa_xbe_fan_rpm{ip=\"$ip\"} > 0)",
     "legendFormat": "enclosure"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_status_info{printer_address=\"$ip\"} == 4",
     "legendFormat": "{{printer_job_name}}"
    }
   ]
  },
  {
   "title": "Active Extruder",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_active_extruder{ip=\"$ip\"} + 1 or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Print Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_print_speed_ratio{printer_address=\"$ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "prusa_cpu_usage{ip=\"$ip\"}",
     "legendFormat": "%"
    },
    { "expr": "vector(100)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MMU status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(printer_name) (prusa_mmu{printer_address=\"$ip\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nozzle Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_nozzle_size_meters{printer_address=\"$ip\"}",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "prusa_5VVoltage{ip=\"$ip\"}",
     "legendFormat": "5V rail"
    },
    {
     "expr": "prusa_24VVoltage{ip=\"$ip\"}",
     "legendFormat": "24V rail"
    },
    {
     "expr": "prusa_volt_bed{ip=\"$ip\"}",
     "legendFormat": "Nozzle"
    },
    {
     "expr": "prusa_volt_nozz{ip=\"$ip\"}",
     "legendFormat": "Bed"
    }
   ]
  },
  {
   "title": "Power consumption (experimental)",
   "type": "timeseries",
   "description": "It is not known if data are correct at this moment",
   "gridPos": { "h": 11, "w": 7, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "abs((prusa_curr_inp{ip=\"$ip\"}* 24)) ",
     "legendFormat": "Watts"
    },
    {
     "expr": "sum(prusa_bed_curr{ip=\"$ip\"})* sum(prusa_24VVoltage{ip=\"$ip\"})",
     "legendFormat": "Bed"
    },
    {
     "expr": "prusa_splitter_5V_current{ip=\"$ip\"}*prusa_5VVoltage{ip=\"$ip\"}",
     "legendFormat": "5V Rail"
    },
    {
     "expr": "sum(prusa_dwarf_heat_curr{ip=\"$ip\"} < 50 or vector(0))  * sum(prusa_24VVoltage{ip=\"$ip\"})",
     "legendFormat": "Dwarfs"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusa_temp_noz{ip=\"$ip\"}",
     "legendFormat": "Nozzle - extruder {{n}}"
    },
    {
     "expr": "prusa_temp_hbr{ip=\"$ip\", a=\"0\"}",
     "legendFormat": "Heatbreak - extruder {{n}}"
    },
    {
     "expr": "prusa_temp_bed{ip=\"$ip\"}",
     "legendFormat": "Heatbed"
    },
    {
     "expr": "prusa_temp_mcu{ip=\"$ip\"}",
     "legendFormat": "MCU"
    },
    {
     "expr": "prusa_chamber_temp{ip=\"$ip\"}",
     "legendFormat": "Chamber"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "prusa_heap_total{ip=\"$ip\"} - prusa_heap_free{ip=\"$ip\"} ",
     "legendFormat": "Used"
    },
    {
     "expr": "prusa_heap_total{ip=\"$ip\"} ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prusa_eth_out_sent{ip=\"$ip\"}[$__rate_interval])",
     "legendFormat": "Ethernet Out"
    },
    {
     "expr": "rate(prusa_eth_in_recv{ip=\"$ip\"}[$__rate_interval])",
     "legendFormat": "Ethernet In"
    },
    {
     "expr": "rate(prusa_esp_in_recv{ip=\"$ip\"}[$__rate_interval])",
     "legendFormat": "ESP In"
    },
    {
     "expr": "rate(prusa_esp_out_sent{ip=\"$ip\"}[$__rate_interval])",
     "legendFormat": "ESP Out"
    }
   ]
  }
 ]
}